name: Google Indexing API Auto Submit

on:
  schedule:
    - cron: '0 12 * * *'
  
  workflow_dispatch:
    inputs:
      max_urls:
        description: '등록할 최대 URL 수'
        required: false
        default: '200'
        type: string
      delay_seconds:
        description: '요청 간 지연시간(초)'
        required: false
        default: '1.0'
        type: string

jobs:
  submit-urls-to-google:
    runs-on: ubuntu-latest
    
    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v4
    
    - name: Python 환경 설정
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: 의존성 설치
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.index.txt
    
    - name: Google 색인 API 실행
      env:
        GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        MAX_URLS: ${{ github.event.inputs.max_urls || '200' }}
        DELAY_SECONDS: ${{ github.event.inputs.delay_seconds || '1.0' }}
      run: |
        python scripts/indexing_bot.py
    
    - name: 결과 알림
      if: always()
      run: |
        if [ ${{ job.status }} = 'success' ]; then
          echo "✅ Google 색인 요청이 성공적으로 완료되었습니다!"
        else
          echo "❌ Google 색인 요청 중 오류가 발생했습니다."
        fi